#!/bin/sh

# Read etckeeper configuration

if [ -z "$ETCKEEPER_CONF_DIR" ]; then
	ETCKEEPER_CONF_DIR=/usr/local/etc/etckeeper
fi

conf="$ETCKEEPER_CONF_DIR/etckeeper.conf"

if [ -e $conf ]; then
	. $conf
fi

for dir in $AUTOCOMMIT_DIRS; do
    env ETCKEEPER_DIR=$dir /usr/local/bin/etckeeper $*
done
if [ "$1" = post-install ]; then
	pl="/var/cache/etckeeper/packagelist"
	rm -f $pl.pre-install $pl.fmt
	rm -f $pl.found-pkgs $pl.found-packages
fi
